version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ollama
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/wellmed_db
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: gemma3:12b
    networks:
      - wellmed-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - wellmed-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Separate service to pull the model after ollama is ready
  ollama-setup:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - wellmed-network
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 10 &&
        echo 'Pulling gemma3:12b model...' &&
        ollama pull gemma3:12b &&
        echo 'Model pulled successfully!'
      "
    restart: "no"

  db:
    image: postgres:15
    container_name: postgres_db_wellmed
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: wellmed_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wellmed-network

volumes:
  postgres_data:
  ollama_data:

networks:
  wellmed-network:
    driver: bridge
    